routes/web.php
//////////////////////// Quotation Controller/////////////////////////////////
Route::get('/quotation/newQuotation/{id}','QuotationController@newQuotation')->name('quotation.newQuotation');
Route::post('/quotation/status','QuotationController@status')->name('quotation.status');
Route::resource('/quotation','QuotationController');


////////////////////// Roles Controller ==////////////////////////
Route::get('/roles/datatable','RolesController@datatable')->name('roles.datatable');
Route::get('/roles/menu/{id}','RolesController@menu')->name('roles.menu');
Route::get('/roles/permission/{id}','RolesController@permission')->name('roles.permission');
Route::post('/roles/status','RolesController@status')->name('roles.status');
Route::resource('/roles','RolesController');


////////////////////// User Menu Controller ==////////////////////////
Route::get('/menu/datatable','UserMenuController@datatable')->name('menu.datatable');
Route::resource('/menu','UserMenuController');

///////////////// permission controller////////////////////////
Route::get('/permission/datatable','PermissionsController@datatable')->name('permission.datatable');
Route::resource('/permission','PermissionsController');


///////////////// user controller////////////////////////
Route::get('/users/datatable','UserController@datatable')->name('users.datatable');
Route::post('/users/editProfile/update','UserController@editProfileUpdate')->name('users.editProfile.update');
Route::get('/users/editProfile/{id}','UserController@editProfile')->name('users.editProfile');
Route::resource('/users','UserController');

Auth::routes();
////////////////////// login customize ============================

Route::post('/login/user','Auth\LoginController@loginUser')->name('login.user');

//////////////// mark all notifications as read /////////////////////////////
Route::get('markAsRead',function(){
    auth()->user()->unreadNotifications->markAsRead();
    return redirect()->back();
})->name('markAllRead');

////////////////////// mark signle notification as read /////////////////////
Route::get('markRead/{id}',function($id){
    $userUnreadNotification = auth()->user()->unreadNotifications->where('id', $id)->first();
    if($userUnreadNotification) {
        $userUnreadNotification->markAsRead();
    }
    return redirect()->back();
})->name('markReadSingle');

//////////////////////// VIEW ALL NOTIFICATIONS /////////////////////////////////
Route::get('/notifications', function () {
    return view('notifications');
})->name('viewAllNotifications');


/////////////////////// biller request update ////////////////////////
Route::get('/billerUpdateRequest/status/{id}','BillerUpdateRequestController@status')->name('billerUpdateRequest.status');
Route::get('/billerUpdateRequest/datatable','BillerUpdateRequestController@datatable')->name('billerUpdateRequest.datatable');
Route::resource('/billerUpdateRequest','BillerUpdateRequestController');


/////////////////////// customer request update ////////////////////////
Route::get('/customerUpdateRequest/status/{id}','CustomerUpdateRequestController@status')->name('customerUpdateRequest.status');
Route::get('/customerUpdateRequest/datatable','CustomerUpdateRequestController@datatable')->name('customerUpdateRequest.datatable');
Route::resource('/customerUpdateRequest','CustomerUpdateRequestController');

/////////////////////// saleperson request update ////////////////////////
Route::get('/salepersonUpdateRequest/status/{id}','SalePersonUpdateRequestController@status')->name('salepersonUpdateRequest.status');
Route::get('/salepersonUpdateRequest/datatable','SalePersonUpdateRequestController@datatable')->name('salepersonUpdateRequest.datatable');
Route::resource('/salepersonUpdateRequest','SalePersonUpdateRequestController');

/////////////////////// supplier request update ////////////////////////
Route::get('/supplierUpdateRequest/status/{id}','SupplierUpdateRequestController@status')->name('supplierUpdateRequest.status');
Route::get('/supplierUpdateRequest/datatable','SupplierUpdateRequestController@datatable')->name('supplierUpdateRequest.datatable');
Route::resource('/supplierUpdateRequest','SupplierUpdateRequestController');


/////////////////////// product request update ////////////////////////
Route::get('/productUpdateRequest/status/{id}','ProductUpdateRequestController@status')->name('productUpdateRequest.status');
Route::get('/productUpdateRequest/datatable','ProductUpdateRequestController@datatable')->name('productUpdateRequest.datatable');
Route::resource('/productUpdateRequest','ProductUpdateRequestController');

//////////////////////// variants controller ///////////////////////////
Route::resource('/variants','VariantsController');

/////////////////////// GST controller /////////////////////////
Route::get('/gst/datatable','GSTController@datatable')->name('gst.datatable');
Route::resource('/gst','GSTController');

/////////////////////// CostType controller /////////////////////////
Route::get('/costtype/datatable','CostTypeController@datatable')->name('costtype.datatable');
Route::resource('/costtype','CostTypeController');


///////////// opening inventory and history/ ///////////////////////////
Route::get('/openingInventory','OpeningInventoryController@viewOpening')->name('openingInventory.viewOpening');
Route::get('/openingInventory/{id}/edit','OpeningInventoryController@edit')->name('openingInventory.edit');
Route::get('/openingInventory/update','OpeningInventoryController@update')->name('openingInventory.update');
Route::get('/history/cost','OpeningInventoryController@avgHistory')->name('history.avgHistory');
Route::get('/history/damages','OpeningInventoryController@damagesHistory')->name('history.damages');

/////////////// Journal Voucher ////////////////////////////
Route::get('/JournalVoucher/search/{amount}/excel/amount','JournalVoucherController@JournalVoucherAmountExcel')->name('JournalVoucher.JournalVoucherAmountExcel');//excel for status
Route::get('/JournalVoucher/search/{desc}/excel/desc','JournalVoucherController@JournalVoucherDescExcel')->name('JournalVoucher.JournalVoucherDescExcel');//excel for status
Route::get('/JournalVoucher/search/{vno}/excel/vno','JournalVoucherController@JournalVoucherVnoExcel')->name('JournalVoucher.JournalVoucherVnoExcel');//excel for status


Route::get('/JournalVoucher/search/{date}/{account}/{check}/excel/date','JournalVoucherController@JournalVoucherDateExcel')->name('JournalVoucher.JournalVoucherDateExcel');//excel for month
Route::get('/JournalVoucher/search/{from}/{to}/{accoount}/{check}/excel/dates','JournalVoucherController@JournalVoucherDatesExcel')->name('JournalVoucher.JournalVoucherDatesExcel');//excel for month
Route::get('/JournalVoucher/search/{index}/excel','JournalVoucherController@JournalVoucherExcel')->name('JournalVoucher.JournalVoucherExcel');//excel for year

Route::get('/JournalVoucher/search/{account}/excel/account','JournalVoucherController@JournalVoucherAccountExcel')->name('JournalVoucher.JournalVoucherAccountExcel');//excel for status
Route::get('/JournalVoucher/search/{year}/{account}/{check}/excel/year','JournalVoucherController@JournalVoucherYearExcel')->name('JournalVoucher.JournalVoucherYearExcel');//excel for year
Route::get('/JournalVoucher/search/{month}/{account}/{check}/excel/month','JournalVoucherController@JournalVoucherMonthExcel')->name('JournalVoucher.JournalVoucherMonthExcel');//excel for month
Route::post('/JournalVoucher/search','JournalVoucherController@search')->name('JournalVoucher.search');
Route::get('/JournalVoucher/excel','JournalVoucherController@excel')->name('JournalVoucher.excel');

Route::get('/JournalVoucher/document/{id}','JournalVoucherController@document')->name('JournalVoucher.document');

Route::post('/JournalVoucher/status','JournalVoucherController@status')->name('JournalVoucher.status');
Route::get('/JournalVoucher/biller/{id}','JournalVoucherController@biller')->name('JournalVoucher.biller');
Route::get('/JournalVoucher/pdf/{id}','JournalVoucherController@pdf')->name('JournalVoucher.pdf');
Route::get('/JournalVoucher/importStructure','JournalVoucherController@importStructure')->name('JournalVoucher.importStructure');
Route::resource('/JournalVoucher','JournalVoucherController');

/////////////////// SALE DOCUMENT CONTROLLER //////////////////////////
Route::post('/addDoc','SaleDocumentController@addDoc')->name('addDoc');
Route::get('/viewDoc/{id}','SaleDocumentController@viewDoc')->name('viewDoc');


/////////////////////// SaleType controller /////////////////////////
Route::get('/saletype/datatable','SaleTypeController@datatable')->name('saletype.datatable');
Route::resource('/saletype','SaleTypeController');


/////////////// import controller ////////////


Route::prefix('import')->group(function () {
    Route::post('journalVoucher','ImportController@journalVoucher')->name('import.journalVoucher');
    Route::post('purchaseOrder','ImportController@purchaseOrder')->name('import.purchaseOrder');
    Route::post('saleOrder','ImportController@saleOrder')->name('import.saleOrder');
    Route::post('receivables','ImportController@receivables')->name('import.receivables');
});
Route::prefix('getproduct')->group(function () {
    Route::get('/{brand?}/{category?}','API\SiteController@getProduct');
});

/////////////////////////// DC ///////////////////////////
Route::post('/dc/delivery','DCController@delivery')->name('saldces.delivery');
Route::post('/dc/status','DCController@status')->name('dc.status');
Route::get('/dc/format/{format}/{biller}','DCController@saleFormat')->name('dc.format');
Route::get('/dc/pdf/{id}','DCController@pdf')->name('dc.pdf');
Route::get('/dc/pdf','DCController@pdf1');
Route::get('/dc/document/{id}','DCController@document')->name('dc.document');
Route::get('/dc/gdn/{id}','DCController@GDN')->name('dc.gdn');
Route::get('/dc/gdr/{no,id}','DCController@GDR')->name('dc.GDR');
Route::get('/dc/gdr1/{no}','DCController@GDR1');
Route::resource('/dc','DCController');

app/GST.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GST extends Model
{
    protected $table = 'gst';
    protected $primaryKey = 'id';
    protected $fillable = [
        'tax',
    ];
}

app/Http/Controllers/GSTController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use App\GST;
use App\User;
use Auth;
use App\Notifications\AddNotification;
use Illuminate\Support\Facades\Notification;

class GSTController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return  view('gst.index');
    }

    public function datatable()
    {
        $gst=GST::all();
        return DataTables::of($gst)->make();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('gst.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'tax' =>  'required'
        ]);
        $gst = GST::create($data);
        $u_name = Auth::user()->name;
        $user = User::where('r_id',config('app.adminId'))->get();
        $data1 = [
            'notification' => 'New Tax has been added by '.$u_name,
            'link' => url('').'/gst',
            'name' => 'View GST List',
        ];
        Notification::send($user, new AddNotification($data1));
        toastr()->success('GST added successfully!');
        return redirect()->back();
    }
}

resources/views/gst/create.blade.php
@extends('layouts.master')
@section('top-styles')
@toastr_css
@section('sidebar-name1')
<li>
    <a href="{{url('')}}/gst">GST</a>
    <i class="fa fa-circle"></i>
</li>
<li>
    <span> Add GST</span>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class=" fa fa-bar-chart font-green"></i>
                        <span class="caption-subject font-green sbold uppercase"> GST</span>
                    </div>

                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form id="gstForm" action="{{  route('gst.store')}} " class="form-horizontal" method="POST" >
                        @csrf
                        <div class="form-body">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-outline">
                                        <label >GST*</label>
                                        <input value="{{ old('tax')}}" class="form-control" type="text" placeholder="Enter GST value" name="tax" >
                                        <span class="text-danger">{{$errors->first('tax') ? 'Enter Value' : null}}</span>
                                    </div>
                                </div>
                            </div>

                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>

@endsection
@section('custom-script')
<script>
    $('#gstForm').validate({
        rules: {
            tsx: {
                required: true,
            },
        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
            error.addClass('invalid-feedback back_error');
            element.closest('.form-outline').append(error);
        },
        highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');

        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
        }
    });
</script>
@toastr_js
@toastr_render
@endsection

resources/views/gst/index.blade.php
@extends('layouts.master')
@section('top-styles')
<style>
    .tableview
    {
        background-color:#F0F0F0;
        padding: 20px;
        border-radius: 5px;
        border:1px solid  #e7ecf1;
    }
</style>
<style>
    #GFG {
        text-decoration: none;
    }
    thead {
	    background-color: #ADD8E6;
    }
    .modal-header{
        background: #32c5d2 !important;
    }
</style>
@toastr_css
<!-- DataTables -->
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

@section('sidebar-name1')
<li>
    <a href="{{url('')}}/gst">GST</a>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- Begin: life time stats -->
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">

                </div>
                <div class="portlet-body">
                    <div class="tabbable-line">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="portlet grey-cascade box">
                                    <div class="portlet-title" style="background: #32c5d2;">
                                        <div class="caption" style="width: -webkit-fill-available; ">
                                            <i class="fa fa-bar-chart font-white"></i>GST List

                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <div class="custom_datatable">

                                            <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th width="7%">S.No</th>
                                                            <th>Tax</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>

@section('custom-script')
@toastr_js
@toastr_render

    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#example').DataTable({
                processing: true,
                order: [[ 0, "desc" ]],
                serverSide: true,
                ajax: '{{route("gst.datatable")}}',
                "columns": [{
                        "data": "id",
                        "defaultContent": ""
                    },
                    {
                        "data": "tax",
                        "defaultContent": ""
                    },
                ],
                "columnDefs": [{
                        "targets": 'no-sort',
                        "orderable": false,
                    },
                    {
                        "targets": 0,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;
                        },
                    },

                ],

            });
        });

    </script>
@endsection
@endsection